### PR TITLE
feat: add swr

### PR DESCRIPTION
**Pull request by TkDodo**

### CODE REVIEW

**Comment by TkDodo** [comment]
FYI, I also tried to upgrade rtk-query to 2.0 beta, but there are type errors I don't understand

**Comment by phryneas** [comment]
Thanks for the PR! 
Tbh., I haven't actively used this after I had done the tests I wanted to do with it, but it's probably a good idea to have some more comparisons in there.
Merging :)

**Comment by TkDodo** [comment]
not sure if there's anything you can do, but rtk-q performs significantly worse than both rq and swr with 1000 nodes, both on mount and on invalidation: it freezes the browser for 1.5+ seconds :/

what I could see is that rtk-q has significantly fewer renders, but they seem to be heavier in computation maybe ?

**Comment by markerikson** [comment]
@TkDodo yeah, there's a couple major factors:

- Immer (and specifically Immer 9 and earlier taking slow paths for copying properties in immutable updates)
- The general architecture of Redux, and that all these updates require dispatches, which also requires running the reducers, notifying subscribers, etc

RTK 2.0 with Immer 10 does improve that perf significantly, but that's also still a worst-case scenario for RTKQ overall.

It's _possible_ we could come up with architectural improvements, and that's something I want to look into for 3.0 after we get 2.0 out the door.

**Pull request merged**
